language: java

# http://levi-wilson.blogspot.com/2012/06/maven-android-travis-ci-and-more.html
before_install:
  - wget http://dl.google.com/android/android-sdk_r18-linux.tgz
  - tar -zxf android-sdk_r18-linux.tgz
  - export ANDROID_HOME=~/builds/emmby/roboguice/android-sdk-linux
  - export PATH=${PATH}:${ANDROID_HOME}/tools:${ANDROID_HOME}/platform-tools
  - android update sdk --filter 1,2 --no-ui --force --all
  - android update sdk --filter 17 --no-ui --force --all
